device         : cuda:0
seed           : 156
dataset        : ogbg-molbbbp
path           : ./datasets/
epochs         : 100
test_epoch     : 0
batch_size     : 64
causaler_lr    : 0.0003
attacker_lr    : 0.0001
l2reg          : 5e-06
repetition     : 1
domain         : size
shift          : covariate
size           : ls
lr_scheduler   : cos
lr_gamma       : 0.1
lr_decay       : 150
lr_min         : 1e-07
milestones     : [3703, 16, 6]
emb_dim        : 300
cau_gamma      : 0.5
cau_reg        : 1
adv_gamma_node : 1.0
adv_gamma_edge : 1.0
cl_rate        : 0.1
adv_dis        : 0.5
adv_reg        : 0.05
fro_layer      : 2
con_reg        : 1
verbose_path   : ./runs
early_stop     : True
patient : 100